### ISSUE TITLE
Can help with own dataset

### ISSUE THREAD

**Issue by nesakeerthi** [pbias/lunet#3]
Hi 
Thanks for the great work and sharing.

Right now i'm VLP16 own dataset.
 can i use it in LU-net or do i need to change the code accordingly?.

because Squeezeseg mentioned as its accepts only Kitti dataset

**Comment by pbias** [comment]
Hi,

I'm not quite familiar with this dataset, but as far as I understand, you
have a LiDAR with only 16 fibers. Therefore, you can expect to create a
range image that has a shape of [16, W].
By simply changing the settings of LU-Net, you might be able to make it
work. Note that the generation of the range image is sensor specific, so
you will have to develop the generation process yourself.

However, because of the successive maxpooling of the network, you might
want to set the " unet_depth" parameter to a lower value, like 2 or 3 to
limit the downsampling of the input image.

Hope it helps,

Bests,

Pierre

Le lun. 20 janv. 2020 à 14:34, nesakeerthi <notifications@github.com> a
écrit :

**Comment by nesakeerthi** [comment]
Thanks for the reply...

Actually the input size is differs for Squeezeseg data size is [64,512,6]

and my data contains VLP16 (16 channel laser) data is [27605,5]

as you mentioned i need to create a genearation file for my dataset.
